### ISSUE TITLE
Build error out of the blue

### ISSUE THREAD

**Issue by nemphys** [moditect/moditect-gradle-plugin#11]
Hello,
I have been using this plugin for many months now, but starting today 10/5, I instantly get the following error when trying to build my project:

> Failed to apply plugin [id 'org.moditect.gradleplugin']
   > Could not create an instance of type org.moditect.gradleplugin.ModitectExtension.
      > org/moditect/spi/log/Log

It is really weird, since the project was building fine until late last night. I just woke up today and cannot build anymore (without making any changes whatsoever).

Any ideas?

EDIT: I changed the version to 1.0.0-beta3 (was beta2) and now it works fine again.

**Comment by siordache** [comment]
The plugin needs to [obtain the moditect-core artifact from jitpack](https://github.com/moditect/moditect-gradle-plugin/issues/3), but we used [`master-SNAPSHOT`](https://github.com/moditect/moditect-gradle-plugin/blob/2bdd53f720358e8f41b826dac6da2d8375e212bd/build.gradle#L34) instead of [a commit hash](https://github.com/moditect/moditect-gradle-plugin/blob/ea0f162e0c5db587f29b46183be1e00f7f2521b1/build.gradle#L34) when specifying the moditect dependency. The [latest snapshot of moditect-core](https://jitpack.io/com/github/moditect/moditect/master-1.0.0.Beta1-g70256af-31/build.log) broke the plugin.
