### ISSUE TITLE
Obtain moditect-core artifact from local repo or Maven Central

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/moditect-gradle-plugin#3]
I.e. avoid the dependency to JitPack.

**Comment by siordache** [comment]
I would like to obtain it from Maven Central, so I will wait for the next release of moditect.
I cannot use the 1.0.0.Beta2 release because the Gradle plugin calls [createCopyWithAutoModuleNameManifestHeader()](https://github.com/moditect/moditect/blob/eef933885bb5a29522acbf821b02da043cf25b60/core/src/main/java/org/moditect/commands/GenerateModuleInfo.java#L117), which was made public only in [PR #79](https://github.com/moditect/moditect/pull/79).

**Comment by gunnarmorling** [comment]
I see. I'll try and cut a release in the next few days then.

**Comment by aalmiray** [comment]
Any updates on this? Would love to stop using a SNAPSHOT build from Jitpack 😄

**Comment by siordache** [comment]
@gunnarmorling Can you publish a new release of moditect?

**Comment by gunnarmorling** [comment]
I won't be able to do it within the next two weeks, as I'll be travelling. Would you perhaps be interested in doing the release, @siordache, if I requested deployment permissions for you at oss.sonatype.org?

**Comment by siordache** [comment]
@gunnarmorling Yes, of course!

**Comment by gunnarmorling** [comment]
That's great, thank you so much, @siordache! What's your user name on oss.sonatype.org? I'll request deploy permissions for you then. Thanks!

**Comment by aalmiray** [comment]
Alternatively @gunnarmorling you could setup a Moditect organization at Bintray and configure auto-deploy to Maven Central 😉

**Comment by siordache** [comment]
@gunnarmorling My user name on oss.sonatype.org is: beryx

**Comment by siordache** [comment]
Fixed in 1.0.0-rc1.

**Comment by gunnarmorling** [comment]
🎉  Woot! Thanks a lot, @siordache!

**Comment by gunnarmorling** [comment]
One question: is moditect-gradle-plugin also deployed to Maven Central?

**Comment by siordache** [comment]
No. It is available in the [Gradle plugins portal](https://plugins.gradle.org/plugin/org.moditect.gradleplugin).
